GET http://localhost:3000/math/multipleprimes

###

POST http://localhost:3000/math/multipleprimes
Content-Type: application/json

{
    "content": 78
}

###
GET http://localhost:3000/math/prime

###

POST http://localhost:3000/math/prime
Content-Type: application/json

{
    "content": 1
}